### ISSUE TITLE
Prepare a version for full sonification interviews

### ISSUE THREAD

**Issue by samreid** [phetsims/waves-intro#7]
At today's sonification meeting, we agreed we need to prepare a version that can be used for student interviews.  This means:

- [x] Addressing known bugs that would interfere with operation
- [x] Add query strings like so:

SR: I’ll create 2 query parameters.  Default for light sound will be off.  Default will be to show a checkbox.
KP: One version: light defaults off, controlled by checkbox
KP: Other version: light has no checkbox and light sound is always on

- [x] Maybe preliminary design team testing or dev testing to make sure things are stable for interviews.

@arouinfar said First week of August would be a good point for interviews.

**Comment by arouinfar** [comment]
@samreid have you made any progress on this? I'd like to schedule the interviews sometime in July 31 - Aug 6 window.

**Comment by samreid** [comment]
@arouinfar I addressed https://github.com/phetsims/wave-interference/issues/407 and added support for the following query parameters:

`?lightSonification=true&lightSonificationCheckbox=true` which can be used in combination.

@arouinfar can you please test master and let me know if the functionality is reasonable?  If it's looking OK, I can create a dev version for interviews.

UPDATE: also a reminder to use `?fullSonification` to turn on the audio subsystem.

**Comment by arouinfar** [comment]
@samreid the query parameters are working nicely. It appears that all pedagogical sounds are hooked up and working properly, but we're still missing some standard UI components. These aren't critical for interviews, but it would be nice to include them if possible.

**Comment by samreid** [comment]
From the July 9 Wave Interference sonification notes, @jbphet said:

> For now, we will use a sim-specific strategy for adding these (UI component sounds) sounds to wave-intro.

My memory is fuzzy--did @jbphet volunteer to implement this part for Waves Intro?  Should I try to help with this part to help us get something ready for interviews as early as July 31?

**Comment by jbphet** [comment]
> [D]id @jbphet volunteer to implement this part for Waves Intro?

Yes, I did.  I'll try to get it done by July 31st 2019.

**Comment by jbphet** [comment]
@emily-phet, @Ashton-Morris, and I discussed whether to add all of the UI sounds to this sim prior to the planned interviews.  @emily-phet made the case that we should focus on whether the sounds with pedagogical intent are working well, and not get distracted with discussions and debates about the common UI sounds.  With this in mind, we decided that the sim as it currently behaves should be used for the interviews.  There are a few UI sounds, such as those for reset all and check boxes, but the remainder of the common UI sounds, such as those for radio buttons, push buttons, screen selection, and pickup/putdown of objects, will not be added at this time.

@arouinfar - please confirm that you're okay with the behavior of the current master version for interviews and, if so, assign this issue back to me or @samreid and we can publish a dev version.

**Comment by arouinfar** [comment]
>  @emily-phet made the case that we should focus on whether the sounds with pedagogical intent are working well, and not get distracted with discussions and debates about the common UI sounds. With this in mind, we decided that the sim as it currently behaves should be used for the interviews. There are a few UI sounds, such as those for reset all and check boxes, but the remainder of the common UI sounds, such as those for radio buttons, push buttons, screen selection, and pickup/putdown of objects, will not be added at this time.

That sounds reasonable to me @jbphet @emily-phet @Ashton-Morris.

> @arouinfar - please confirm that you're okay with the behavior of the current master version for interviews and, if so, assign this issue back to me or @samreid and we can publish a dev version.

No need to publish a new dev version. @samreid published dev.9 for QA testing earlier today, and the sonification query parameters I need for interviews are all working as intended.
